version: "2"

services:

  rabbitmq:
    # Message broker for Celery
    image: rabbitmq:3.7-management-alpine
    # ports:
    #   # The rabbitMQ management plugin - running on http://localhost:15672
    #   - "15672:15672"
    #   - "5672:5672"
    volumes:
      - "./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf"
      - ./rabbitmq_data:/var/lib/rabbitmq
  celery:
    # Python application which run the Celery worker
    build:
      context: celery_app
      dockerfile: docker/celery.dockerfile
    environment:
      - "BROKER=amqp://celery_user:secret@rabbitmq:5672/celery_app"
    restart: always
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - './celery_app:/celery_app'

  flower:
    # Monitoring application - running on http://localhost:5555
    build:
      context: celery_app
      dockerfile: docker/flower.dockerfile
    environment:
      - "BROKER=amqp://celery_user:secret@rabbitmq:5672/celery_app"
    links:
      - celery
      - rabbitmq
    restart: always
    volumes:
      - './celery_app:/celery_app'
    depends_on:
      - celery
    ports:
      - "5555:5555"
